//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Runtime.Serialization;

namespace WCFCoreInterno
{

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "SI_Rastro", Namespace = "http://schemas.datacontract.org/2004/07/")]
    public partial class SI_Rastro : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private int CanalField;

        private string IPField;

        private string UsuarioField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Canal
        {
            get
            {
                return this.CanalField;
            }
            set
            {
                this.CanalField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IP
        {
            get
            {
                return this.IPField;
            }
            set
            {
                this.IPField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usuario
        {
            get
            {
                return this.UsuarioField;
            }
            set
            {
                this.UsuarioField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "CL_DatosTransaccion", Namespace = "http://schemas.datacontract.org/2004/07/")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CL_Transaccion))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CL_ActualizaTransaccion))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TransaccionRechazada))]
    public partial class CL_DatosTransaccion : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private int CodigoMonedaField;

        private int CodigoServicioField;

        private string CuentaIBANField;

        private string IdRelacionClienteField;

        private string IdentificacionField;

        private decimal MontoField;
        [System.Runtime.Serialization.DataMemberAttribute()] 
        public List<CL_Adicional_Info> InformacionAdicional { get; set; }
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoMoneda
        {
            get
            {
                return this.CodigoMonedaField;
            }
            set
            {
                this.CodigoMonedaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoServicio
        {
            get
            {
                return this.CodigoServicioField;
            }
            set
            {
                this.CodigoServicioField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CuentaIBAN
        {
            get
            {
                return this.CuentaIBANField;
            }
            set
            {
                this.CuentaIBANField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdRelacionCliente
        {
            get
            {
                return this.IdRelacionClienteField;
            }
            set
            {
                this.IdRelacionClienteField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Identificacion
        {
            get
            {
                return this.IdentificacionField;
            }
            set
            {
                this.IdentificacionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Monto
        {
            get
            {
                return this.MontoField;
            }
            set
            {
                this.MontoField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "CL_Transaccion", Namespace = "http://schemas.datacontract.org/2004/07/")]
    public partial class CL_Transaccion : CL_DatosTransaccion
    {

        private int CentroCostoField;

        private int CodEntidadField;

        private string CodigoReferenciaField;

        private int ComprobanteCGPField;

        private string CuentaIBANContraparteField;

        private string DescripcionField;

        private System.DateTime FechaCicloField;

        private string IdOrigenField;

        private string IdentificacionContraparteField;

        private int MonedaComisionField;

        private decimal MontoComisionField;

        private string NombreOrigenField;

        private string ServicioField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CentroCosto
        {
            get
            {
                return this.CentroCostoField;
            }
            set
            {
                this.CentroCostoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodEntidad
        {
            get
            {
                return this.CodEntidadField;
            }
            set
            {
                this.CodEntidadField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoReferencia
        {
            get
            {
                return this.CodigoReferenciaField;
            }
            set
            {
                this.CodigoReferenciaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ComprobanteCGP
        {
            get
            {
                return this.ComprobanteCGPField;
            }
            set
            {
                this.ComprobanteCGPField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CuentaIBANContraparte
        {
            get
            {
                return this.CuentaIBANContraparteField;
            }
            set
            {
                this.CuentaIBANContraparteField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaCiclo
        {
            get
            {
                return this.FechaCicloField;
            }
            set
            {
                this.FechaCicloField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdOrigen
        {
            get
            {
                return this.IdOrigenField;
            }
            set
            {
                this.IdOrigenField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdentificacionContraparte
        {
            get
            {
                return this.IdentificacionContraparteField;
            }
            set
            {
                this.IdentificacionContraparteField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MonedaComision
        {
            get
            {
                return this.MonedaComisionField;
            }
            set
            {
                this.MonedaComisionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MontoComision
        {
            get
            {
                return this.MontoComisionField;
            }
            set
            {
                this.MontoComisionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreOrigen
        {
            get
            {
                return this.NombreOrigenField;
            }
            set
            {
                this.NombreOrigenField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Servicio
        {
            get
            {
                return this.ServicioField;
            }
            set
            {
                this.ServicioField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "CL_ActualizaTransaccion", Namespace = "http://schemas.datacontract.org/2004/07/")]
    public partial class CL_ActualizaTransaccion : CL_DatosTransaccion
    {

        private System.Nullable<int> CodigoRechazoSINPEField;

        private string CodigoReferenciaField;

        private int ComprobanteCGPField;

        private string ComprobanteInternoField;

        private string DescripcionRechazoField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CodigoRechazoSINPE
        {
            get
            {
                return this.CodigoRechazoSINPEField;
            }
            set
            {
                this.CodigoRechazoSINPEField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoReferencia
        {
            get
            {
                return this.CodigoReferenciaField;
            }
            set
            {
                this.CodigoReferenciaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ComprobanteCGP
        {
            get
            {
                return this.ComprobanteCGPField;
            }
            set
            {
                this.ComprobanteCGPField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ComprobanteInterno
        {
            get
            {
                return this.ComprobanteInternoField;
            }
            set
            {
                this.ComprobanteInternoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescripcionRechazo
        {
            get
            {
                return this.DescripcionRechazoField;
            }
            set
            {
                this.DescripcionRechazoField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "TransaccionRechazada", Namespace = "http://schemas.datacontract.org/2004/07/")]
    public partial class TransaccionRechazada : CL_DatosTransaccion
    {

        private System.Nullable<int> CodigoRechazoSINPEField;

        private string CodigoReferenciaField;

        private int ComprobanteCGPField;

        private string ComprobanteInternoField;

        private string DescripcionRechazoField;

        private int MonedaComisionField;

        private decimal MontoComisionField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CodigoRechazoSINPE
        {
            get
            {
                return this.CodigoRechazoSINPEField;
            }
            set
            {
                this.CodigoRechazoSINPEField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoReferencia
        {
            get
            {
                return this.CodigoReferenciaField;
            }
            set
            {
                this.CodigoReferenciaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ComprobanteCGP
        {
            get
            {
                return this.ComprobanteCGPField;
            }
            set
            {
                this.ComprobanteCGPField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ComprobanteInterno
        {
            get
            {
                return this.ComprobanteInternoField;
            }
            set
            {
                this.ComprobanteInternoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescripcionRechazo
        {
            get
            {
                return this.DescripcionRechazoField;
            }
            set
            {
                this.DescripcionRechazoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MonedaComision
        {
            get
            {
                return this.MonedaComisionField;
            }
            set
            {
                this.MonedaComisionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MontoComision
        {
            get
            {
                return this.MontoComisionField;
            }
            set
            {
                this.MontoComisionField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "CL_ResultadoValidacion", Namespace = "http://schemas.datacontract.org/2004/07/")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CL_RespuestaTransaccion))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CL_RespuestaNotificacion))]
    public partial class CL_ResultadoValidacion : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string IdRelacionClienteField;

        private CL_Adicional_Info[] InformacionAdicionalField;

        private System.Nullable<int> MotivoErrorField;

        private E_Resultado ResultadoField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdRelacionCliente
        {
            get
            {
                return this.IdRelacionClienteField;
            }
            set
            {
                this.IdRelacionClienteField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public CL_Adicional_Info[] InformacionAdicional
        {
            get
            {
                return this.InformacionAdicionalField;
            }
            set
            {
                this.InformacionAdicionalField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MotivoError
        {
            get
            {
                return this.MotivoErrorField;
            }
            set
            {
                this.MotivoErrorField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public E_Resultado Resultado
        {
            get
            {
                return this.ResultadoField;
            }
            set
            {
                this.ResultadoField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "CL_RespuestaTransaccion", Namespace = "http://schemas.datacontract.org/2004/07/")]
    public partial class CL_RespuestaTransaccion : CL_ResultadoValidacion
    {

        private string ComprobanteInternoField;

        private CL_Adicional_Info[] InformacionAdicional1Field;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ComprobanteInterno
        {
            get
            {
                return this.ComprobanteInternoField;
            }
            set
            {
                this.ComprobanteInternoField = value;
            }
        }        
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "CL_Error", Namespace = "http://schemas.datacontract.org/2004/07/")]
    public class CL_Error
    {
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumError { get; set; }
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion { get; set; }
        public CL_Error()
        {
        }


    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "CL_CuentaIBAN", Namespace = "http://schemas.datacontract.org/2004/07/")]
    public class CL_CuentaIBAN
    {
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CuentaIBAN { get; set; }
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdTitular { get; set; }
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TipoId { get; set; }
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreTitular { get; set; }
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Moneda { get; set; }
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DesProducto { get; set; }
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Estado { get; set; }
        public CL_CuentaIBAN()
        {
            //
            // TODO: Agregar aquí la lógica del constructor
            //
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "CuentaIBAN_Response", Namespace = "http://schemas.datacontract.org/2004/07/")]
    public class CuentaIBAN_Response
    {
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Resultado { get; set; }
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CL_CuentaIBAN CuentaIBAN { get; set; }
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<CL_Error> Errores { get; set; }
        public CuentaIBAN_Response()
        {
            Errores = new List<CL_Error>();
            CuentaIBAN = new CL_CuentaIBAN();
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "CL_AutorizacionPerfilTrx", Namespace = "http://schemas.datacontract.org/2004/07/")]
    public partial class CL_AutorizacionPerfilTrx : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Estado { get; set; }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumRefProcesamiento { get; set; }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodMotivoRechazo { get; set; }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MotivoRechazo { get; set; }

        [System.Runtime.Serialization.DataMemberAttribute()]
        private List<CL_Adicional_Info> DatosAdicionalesField;

        
        public List<CL_Adicional_Info> DatosAdicionales
        {
            get
            {
                return this.DatosAdicionalesField;
            }
            set
            {
                this.DatosAdicionalesField = value;
            }
        }

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        public CL_AutorizacionPerfilTrx()
        {
            DatosAdicionales = new List<CL_Adicional_Info>();
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ValidacionPerfilTrx_Request", Namespace = "http://schemas.datacontract.org/2004/07/")]
    public class ValidacionPerfilTrx_Request : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdCliente { get; set; }
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TipoIdCliente { get; set; }
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreCliente { get; set; }
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CuentaIBAN { get; set; }
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdClienteEntContraparte { get; set; }
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TipoIdClienteEntContraparte { get; set; }
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreClienteContraparte { get; set; }
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IBANClienteEntContraparte { get; set; }
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Servicio { get; set; }
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Modalidad { get; set; }
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoMovimiento { get; set; }
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Monto { get; set; }
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Moneda { get; set; }
        public ValidacionPerfilTrx_Request()
        {
        }
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ValidacionPerfilTrx_Response", Namespace = "http://schemas.datacontract.org/2004/07/")]
    public class ValidacionPerfilTrx_Response
    {
        public bool ResultadoField { get; set; }
        public CL_AutorizacionPerfilTrx AutorizacionField { get; set; }

        public List<CL_Error> ErroresField { get; set; }
        public ValidacionPerfilTrx_Response()
        {
            AutorizacionField = new CL_AutorizacionPerfilTrx();
            ErroresField = new List<CL_Error>();
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public CL_AutorizacionPerfilTrx Autorizacion
        {
            get
            {
                return this.AutorizacionField;
            }
            set
            {
                this.AutorizacionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<CL_Error> Errores
        {
            get
            {
                return this.ErroresField;
            }
            set
            {
                this.ErroresField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Resultado
        {
            get
            {
                return this.ResultadoField;
            }
            set
            {
                this.ResultadoField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "CL_RespuestaNotificacion", Namespace = "http://schemas.datacontract.org/2004/07/")]
    public partial class CL_RespuestaNotificacion : CL_ResultadoValidacion
    {

        private E_Preferencia E_PreferenciaField;

        private string EmailField;

        private string NombreClienteField;

        private string TelefonoField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public E_Preferencia E_Preferencia
        {
            get
            {
                return this.E_PreferenciaField;
            }
            set
            {
                this.E_PreferenciaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreCliente
        {
            get
            {
                return this.NombreClienteField;
            }
            set
            {
                this.NombreClienteField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono
        {
            get
            {
                return this.TelefonoField;
            }
            set
            {
                this.TelefonoField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "CL_Adicional_Info", Namespace = "http://schemas.datacontract.org/2004/07/")]
    public partial class CL_Adicional_Info : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private bool MostrarField;

        private string NombreField;

        private string NombreFisicoField;

        private string ValorField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Mostrar
        {
            get
            {
                return this.MostrarField;
            }
            set
            {
                this.MostrarField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreFisico
        {
            get
            {
                return this.NombreFisicoField;
            }
            set
            {
                this.NombreFisicoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Valor
        {
            get
            {
                return this.ValorField;
            }
            set
            {
                this.ValorField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "E_Resultado", Namespace = "http://schemas.datacontract.org/2004/07/")]
    public enum E_Resultado : int
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Exitoso = 0,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Rechazo = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 2,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "E_Preferencia", Namespace = "http://schemas.datacontract.org/2004/07/")]
    public enum E_Preferencia : int
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Correo = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        SMS = 2,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ambos = 3,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ninguno = 4,
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "CL_ValidaCuenta", Namespace = "http://schemas.datacontract.org/2004/07/")]
    public partial class CL_ValidaCuenta : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private System.Nullable<int> MotivoErrorField;

        private E_Resultado ResultadoField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MotivoError
        {
            get
            {
                return this.MotivoErrorField;
            }
            set
            {
                this.MotivoErrorField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public E_Resultado Resultado
        {
            get
            {
                return this.ResultadoField;
            }
            set
            {
                this.ResultadoField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "CL_ObtieneInfoCuenta", Namespace = "http://schemas.datacontract.org/2004/07/")]
    public partial class CL_ObtieneInfoCuenta : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private E_Estado EstadoField;

        private int MonedaField;

        private System.Nullable<int> MotivoErrorField;

        private string NombreTitularField;

        private E_Resultado ResultadoField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public E_Estado Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Moneda
        {
            get
            {
                return this.MonedaField;
            }
            set
            {
                this.MonedaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MotivoError
        {
            get
            {
                return this.MotivoErrorField;
            }
            set
            {
                this.MotivoErrorField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreTitular
        {
            get
            {
                return this.NombreTitularField;
            }
            set
            {
                this.NombreTitularField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public E_Resultado Resultado
        {
            get
            {
                return this.ResultadoField;
            }
            set
            {
                this.ResultadoField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "E_Estado", Namespace = "http://schemas.datacontract.org/2004/07/")]
    public enum E_Estado : int
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Activa = 0,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cerrada = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Bloqueada = 2,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoActiva = 3,
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "CL_ResultadoActualizacion", Namespace = "http://schemas.datacontract.org/2004/07/")]
    public partial class CL_ResultadoActualizacion : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string IdRelacionClienteField;

        private E_ResultadoActualizacion ResultadoField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdRelacionCliente
        {
            get
            {
                return this.IdRelacionClienteField;
            }
            set
            {
                this.IdRelacionClienteField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public E_ResultadoActualizacion Resultado
        {
            get
            {
                return this.ResultadoField;
            }
            set
            {
                this.ResultadoField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "E_ResultadoActualizacion", Namespace = "http://schemas.datacontract.org/2004/07/")]
    public enum E_ResultadoActualizacion : int
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Exitoso = 0,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoExiste = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoPermitido = 2,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 3,
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "CL_InformacionCliente", Namespace = "http://schemas.datacontract.org/2004/07/")]
    public partial class CL_InformacionCliente : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private bool ExisteField;

        private string NombreField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Existe
        {
            get
            {
                return this.ExisteField;
            }
            set
            {
                this.ExisteField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "CuentaIBAN_Request", Namespace = "http://schemas.datacontract.org/2004/07/")]
    public class CuentaIBAN_Request : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        private string CuentaIBANField;
        public CuentaIBAN_Request()
        {

        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CuentaIBAN
        {
            get
            {
                return this.CuentaIBANField;
            }
            set
            {
                this.CuentaIBANField = value;
            }
        }

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "CL_ProductoCliente", Namespace = "http://schemas.datacontract.org/2004/07/")]
    public partial class CL_ProductoCliente : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private int CodigoMonedaField;

        private string CuentaClienteField;

        private decimal CuotaField;

        private string DescripcionServicioField;

        private E_MovimientosPermitidosProducto MovimientosPermitidosField;

        private decimal SaldoField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoMoneda
        {
            get
            {
                return this.CodigoMonedaField;
            }
            set
            {
                this.CodigoMonedaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CuentaCliente
        {
            get
            {
                return this.CuentaClienteField;
            }
            set
            {
                this.CuentaClienteField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Cuota
        {
            get
            {
                return this.CuotaField;
            }
            set
            {
                this.CuotaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescripcionServicio
        {
            get
            {
                return this.DescripcionServicioField;
            }
            set
            {
                this.DescripcionServicioField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public E_MovimientosPermitidosProducto MovimientosPermitidos
        {
            get
            {
                return this.MovimientosPermitidosField;
            }
            set
            {
                this.MovimientosPermitidosField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Saldo
        {
            get
            {
                return this.SaldoField;
            }
            set
            {
                this.SaldoField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "E_MovimientosPermitidosProducto", Namespace = "http://schemas.datacontract.org/2004/07/")]
    public enum E_MovimientosPermitidosProducto : int
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Acreditar = 0,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Debitar = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ambos = 2,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ninguno = 3,
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "CL_ResultadoTipoCambio", Namespace = "http://schemas.datacontract.org/2004/07/")]
    public partial class CL_ResultadoTipoCambio : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private decimal TipoCambioAplicadoField;

        private decimal montoTotalField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TipoCambioAplicado
        {
            get
            {
                return this.TipoCambioAplicadoField;
            }
            set
            {
                this.TipoCambioAplicadoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal montoTotal
        {
            get
            {
                return this.montoTotalField;
            }
            set
            {
                this.montoTotalField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "CL_Notificacion", Namespace = "http://schemas.datacontract.org/2004/07/")]
    public partial class CL_Notificacion : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string CuentaIBANField;

        private string IdentificacionField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CuentaIBAN
        {
            get
            {
                return this.CuentaIBANField;
            }
            set
            {
                this.CuentaIBANField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Identificacion
        {
            get
            {
                return this.IdentificacionField;
            }
            set
            {
                this.IdentificacionField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://prosoft.CGPbackOffice/", ConfigurationName = "ICoreInterno")]
    public interface ICoreInterno
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://prosoft.CGPbackOffice/ICoreInterno/ServicioDisponible", ReplyAction = "http://prosoft.CGPbackOffice/ICoreInterno/ServicioDisponibleResponse")]
        bool ServicioDisponible(int CodEmpresa);

        [System.ServiceModel.OperationContractAttribute(Action = "http://prosoft.CGPbackOffice/ICoreInterno/ValidarPerfilTransaccional", ReplyAction = "http://prosoft.CGPbackOffice/ICoreInterno/ValidarPerfilTransaccionalResponse")]
        ValidacionPerfilTrx_Response ValidarPerfilTransaccional(ValidacionPerfilTrx_Request transaccion);

        [System.ServiceModel.OperationContractAttribute(Action = "http://prosoft.CGPbackOffice/ICoreInterno/ObtenerCuentaIBAN", ReplyAction = "http://prosoft.CGPbackOffice/ICoreInterno/ObtenerCuentaIBANResponse")]
        CuentaIBAN_Response ObtenerCuentaIBAN(int CodEmpresa,CuentaIBAN_Request DatosCuenta);

        [System.ServiceModel.OperationContractAttribute(Action = "http://prosoft.CGPbackOffice/ICoreInterno/ValidaDebitos", ReplyAction = "http://prosoft.CGPbackOffice/ICoreInterno/ValidaDebitosResponse")]
        CL_ResultadoValidacion[] ValidaDebitos(SI_Rastro rastro, CL_DatosTransaccion[] transacciones);

        [System.ServiceModel.OperationContractAttribute(Action = "http://prosoft.CGPbackOffice/ICoreInterno/ValidaCreditos", ReplyAction = "http://prosoft.CGPbackOffice/ICoreInterno/ValidaCreditosResponse")]
        CL_ResultadoValidacion[] ValidaCreditos(SI_Rastro rastro, CL_DatosTransaccion[] transacciones);

        [System.ServiceModel.OperationContractAttribute(Action = "http://prosoft.CGPbackOffice/ICoreInterno/ValidaCuenta", ReplyAction = "http://prosoft.CGPbackOffice/ICoreInterno/ValidaCuentaResponse")]
        CL_ValidaCuenta ValidaCuenta(string Identificacion, string CuentaIBAN, int CodigoMoneda);

        [System.ServiceModel.OperationContractAttribute(Action = "http://prosoft.CGPbackOffice/ICoreInterno/ObtieneInfoCuenta", ReplyAction = "http://prosoft.CGPbackOffice/ICoreInterno/ObtieneInfoCuentaResponse")]
        CL_ObtieneInfoCuenta ObtieneInfoCuenta(string Identificacion, string CuentaIBAN);

        [System.ServiceModel.OperationContractAttribute(Action = "http://prosoft.CGPbackOffice/ICoreInterno/ObtieneEstadoTransaccion", ReplyAction = "http://prosoft.CGPbackOffice/ICoreInterno/ObtieneEstadoTransaccionResponse")]
        ObtieneEstadoTransaccionResponse ObtieneEstadoTransaccion(ObtieneEstadoTransaccionRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://prosoft.CGPbackOffice/ICoreInterno/AplicaDebitosCongelados", ReplyAction = "http://prosoft.CGPbackOffice/ICoreInterno/AplicaDebitosCongeladosResponse")]
        CL_RespuestaTransaccion[] AplicaDebitosCongelados(SI_Rastro rastro, CL_Transaccion[] transacciones);

        [System.ServiceModel.OperationContractAttribute(Action = "http://prosoft.CGPbackOffice/ICoreInterno/AplicaCreditosCongelados", ReplyAction = "http://prosoft.CGPbackOffice/ICoreInterno/AplicaCreditosCongeladosResponse")]
        CL_RespuestaTransaccion[] AplicaCreditosCongelados(SI_Rastro rastro, CL_Transaccion[] transacciones);

        [System.ServiceModel.OperationContractAttribute(Action = "http://prosoft.CGPbackOffice/ICoreInterno/ConfirmaCreditosCongelados", ReplyAction = "http://prosoft.CGPbackOffice/ICoreInterno/ConfirmaCreditosCongeladosResponse")]
        CL_ResultadoActualizacion[] ConfirmaCreditosCongelados(SI_Rastro rastro, CL_ActualizaTransaccion[] transacciones);

        [System.ServiceModel.OperationContractAttribute(Action = "http://prosoft.CGPbackOffice/ICoreInterno/ConfirmaDebitosCongelados", ReplyAction = "http://prosoft.CGPbackOffice/ICoreInterno/ConfirmaDebitosCongeladosResponse")]
        CL_ResultadoActualizacion[] ConfirmaDebitosCongelados(SI_Rastro rastro, CL_ActualizaTransaccion[] transacciones);

        [System.ServiceModel.OperationContractAttribute(Action = "http://prosoft.CGPbackOffice/ICoreInterno/AplicaTransferenciasFirmes", ReplyAction = "http://prosoft.CGPbackOffice/ICoreInterno/AplicaTransferenciasFirmesResponse")]
        CL_RespuestaTransaccion[] AplicaTransferenciasFirmes(SI_Rastro rastro, CL_Transaccion[] transacciones);

        [System.ServiceModel.OperationContractAttribute(Action = "http://prosoft.CGPbackOffice/ICoreInterno/SaldoDisponible", ReplyAction = "http://prosoft.CGPbackOffice/ICoreInterno/SaldoDisponibleResponse")]
        SaldoDisponibleResponse SaldoDisponible(SaldoDisponibleRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://prosoft.CGPbackOffice/ICoreInterno/ComisionRespectiva", ReplyAction = "http://prosoft.CGPbackOffice/ICoreInterno/ComisionRespectivaResponse")]
        ComisionRespectivaResponse ComisionRespectiva(ComisionRespectivaRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://prosoft.CGPbackOffice/ICoreInterno/ReversaCreditos", ReplyAction = "http://prosoft.CGPbackOffice/ICoreInterno/ReversaCreditosResponse")]
        CL_ResultadoActualizacion[] ReversaCreditos(SI_Rastro rastro, TransaccionRechazada[] transacciones);

        [System.ServiceModel.OperationContractAttribute(Action = "http://prosoft.CGPbackOffice/ICoreInterno/ReversaDebitos", ReplyAction = "http://prosoft.CGPbackOffice/ICoreInterno/ReversaDebitosResponse")]
        CL_ResultadoActualizacion[] ReversaDebitos(SI_Rastro rastro, TransaccionRechazada[] transacciones);

        [System.ServiceModel.OperationContractAttribute(Action = "http://prosoft.CGPbackOffice/ICoreInterno/ObtenerInformacionCliente", ReplyAction = "http://prosoft.CGPbackOffice/ICoreInterno/ObtenerInformacionClienteResponse")]
        ObtenerInformacionClienteResponse ObtenerInformacionCliente(ObtenerInformacionClienteRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://prosoft.CGPbackOffice/ICoreInterno/ObtenerProductosPorCliente", ReplyAction = "http://prosoft.CGPbackOffice/ICoreInterno/ObtenerProductosPorClienteResponse")]
        ObtenerProductosPorClienteResponse ObtenerProductosPorCliente(ObtenerProductosPorClienteRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://prosoft.CGPbackOffice/ICoreInterno/ObtenerTipoCambio", ReplyAction = "http://prosoft.CGPbackOffice/ICoreInterno/ObtenerTipoCambioResponse")]
        CL_ResultadoTipoCambio ObtenerTipoCambio(SI_Rastro Rastro, int CodigoServicio, string CuentaOrigen, string CuentaDestino, decimal Monto, int Moneda);

        [System.ServiceModel.OperationContractAttribute(Action = "http://prosoft.CGPbackOffice/ICoreInterno/ActualizarFechaCiclo", ReplyAction = "http://prosoft.CGPbackOffice/ICoreInterno/ActualizarFechaCicloResponse")]
        bool ActualizarFechaCiclo(int ComprobanteCGP, string DocumentoSistemaInterno, int ServicioSINPE, System.DateTime FechaCiclo, string CodigoReferenciaAnterior, string CodigoReferenciaNuevo);

        [System.ServiceModel.OperationContractAttribute(Action = "http://prosoft.CGPbackOffice/ICoreInterno/LiquidarCiclo", ReplyAction = "http://prosoft.CGPbackOffice/ICoreInterno/LiquidarCicloResponse")]
        bool LiquidarCiclo(int[] EntidadesAplazadas, int ServicioSINPE, string Modalidad, System.DateTime FechaCiclo);

        [System.ServiceModel.OperationContractAttribute(Action = "http://prosoft.CGPbackOffice/ICoreInterno/PreferenciasNotificacion", ReplyAction = "http://prosoft.CGPbackOffice/ICoreInterno/PreferenciasNotificacionResponse")]
        CL_RespuestaNotificacion[] PreferenciasNotificacion(SI_Rastro rastro, CL_Notificacion[] notificacion);

    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "ObtieneEstadoTransaccion", WrapperNamespace = "http://prosoft.CGPbackOffice/", IsWrapped = true)]
    public partial class ObtieneEstadoTransaccionRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://prosoft.CGPbackOffice/", Order = 0)]
        public string CodigoReferenciaSINPE;

        public ObtieneEstadoTransaccionRequest()
        {
        }

        public ObtieneEstadoTransaccionRequest(string CodigoReferenciaSINPE)
        {
            this.CodigoReferenciaSINPE = CodigoReferenciaSINPE;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "ObtieneEstadoTransaccionResponse", WrapperNamespace = "http://prosoft.CGPbackOffice/", IsWrapped = true)]
    public partial class ObtieneEstadoTransaccionResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://prosoft.CGPbackOffice/", Order = 0)]
        public bool ObtieneEstadoTransaccionResult;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://prosoft.CGPbackOffice/", Order = 1)]
        public string ComprobanteInterno;

        public ObtieneEstadoTransaccionResponse()
        {
        }

        public ObtieneEstadoTransaccionResponse(bool ObtieneEstadoTransaccionResult, string ComprobanteInterno)
        {
            this.ObtieneEstadoTransaccionResult = ObtieneEstadoTransaccionResult;
            this.ComprobanteInterno = ComprobanteInterno;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "SaldoDisponible", WrapperNamespace = "http://prosoft.CGPbackOffice/", IsWrapped = true)]
    public partial class SaldoDisponibleRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://prosoft.CGPbackOffice/", Order = 0)]
        public SI_Rastro rastro;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://prosoft.CGPbackOffice/", Order = 1)]
        public string cuentaIBAN;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://prosoft.CGPbackOffice/", Order = 2)]
        public string identificacion;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://prosoft.CGPbackOffice/", Order = 3)]
        public int codigoMoneda;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://prosoft.CGPbackOffice/", Order = 4)]
        public decimal monto;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://prosoft.CGPbackOffice/", Order = 5)]
        public int codigoServicio;

        public SaldoDisponibleRequest()
        {
        }

        public SaldoDisponibleRequest(SI_Rastro rastro, string cuentaIBAN, string identificacion, int codigoMoneda, decimal monto, int codigoServicio)
        {
            this.rastro = rastro;
            this.cuentaIBAN = cuentaIBAN;
            this.identificacion = identificacion;
            this.codigoMoneda = codigoMoneda;
            this.monto = monto;
            this.codigoServicio = codigoServicio;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "SaldoDisponibleResponse", WrapperNamespace = "http://prosoft.CGPbackOffice/", IsWrapped = true)]
    public partial class SaldoDisponibleResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://prosoft.CGPbackOffice/", Order = 0)]
        public E_Resultado SaldoDisponibleResult;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://prosoft.CGPbackOffice/", Order = 1)]
        public bool disponible;

        public SaldoDisponibleResponse()
        {
        }

        public SaldoDisponibleResponse(E_Resultado SaldoDisponibleResult, bool disponible)
        {
            this.SaldoDisponibleResult = SaldoDisponibleResult;
            this.disponible = disponible;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "ComisionRespectiva", WrapperNamespace = "http://prosoft.CGPbackOffice/", IsWrapped = true)]
    public partial class ComisionRespectivaRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://prosoft.CGPbackOffice/", Order = 0)]
        public SI_Rastro rastro;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://prosoft.CGPbackOffice/", Order = 1)]
        public string cuentaIBAN;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://prosoft.CGPbackOffice/", Order = 2)]
        public string identificacion;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://prosoft.CGPbackOffice/", Order = 3)]
        public int codigoMoneda;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://prosoft.CGPbackOffice/", Order = 4)]
        public decimal monto;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://prosoft.CGPbackOffice/", Order = 5)]
        public int codigoServicio;

        public ComisionRespectivaRequest()
        {
        }

        public ComisionRespectivaRequest(SI_Rastro rastro, string cuentaIBAN, string identificacion, int codigoMoneda, decimal monto, int codigoServicio)
        {
            this.rastro = rastro;
            this.cuentaIBAN = cuentaIBAN;
            this.identificacion = identificacion;
            this.codigoMoneda = codigoMoneda;
            this.monto = monto;
            this.codigoServicio = codigoServicio;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "ComisionRespectivaResponse", WrapperNamespace = "http://prosoft.CGPbackOffice/", IsWrapped = true)]
    public partial class ComisionRespectivaResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://prosoft.CGPbackOffice/", Order = 0)]
        public E_Resultado ComisionRespectivaResult;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://prosoft.CGPbackOffice/", Order = 1)]
        public decimal comision;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://prosoft.CGPbackOffice/", Order = 2)]
        public int codigoMonedaComision;

        public ComisionRespectivaResponse()
        {
        }

        public ComisionRespectivaResponse(E_Resultado ComisionRespectivaResult, decimal comision, int codigoMonedaComision)
        {
            this.ComisionRespectivaResult = ComisionRespectivaResult;
            this.comision = comision;
            this.codigoMonedaComision = codigoMonedaComision;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "ObtenerInformacionCliente", WrapperNamespace = "http://prosoft.CGPbackOffice/", IsWrapped = true)]
    public partial class ObtenerInformacionClienteRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://prosoft.CGPbackOffice/", Order = 0)]
        public string identificacion;

        public ObtenerInformacionClienteRequest()
        {
        }

        public ObtenerInformacionClienteRequest(string identificacion)
        {
            this.identificacion = identificacion;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "ObtenerInformacionClienteResponse", WrapperNamespace = "http://prosoft.CGPbackOffice/", IsWrapped = true)]
    public partial class ObtenerInformacionClienteResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://prosoft.CGPbackOffice/", Order = 0)]
        public E_Resultado ObtenerInformacionClienteResult;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://prosoft.CGPbackOffice/", Order = 1)]
        public CL_InformacionCliente informacionCliente;

        public ObtenerInformacionClienteResponse()
        {
        }

        public ObtenerInformacionClienteResponse(E_Resultado ObtenerInformacionClienteResult, CL_InformacionCliente informacionCliente)
        {
            this.ObtenerInformacionClienteResult = ObtenerInformacionClienteResult;
            this.informacionCliente = informacionCliente;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "ObtenerProductosPorCliente", WrapperNamespace = "http://prosoft.CGPbackOffice/", IsWrapped = true)]
    public partial class ObtenerProductosPorClienteRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://prosoft.CGPbackOffice/", Order = 0)]
        public string identificacion;

        public ObtenerProductosPorClienteRequest()
        {
        }

        public ObtenerProductosPorClienteRequest(string identificacion)
        {
            this.identificacion = identificacion;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "ObtenerProductosPorClienteResponse", WrapperNamespace = "http://prosoft.CGPbackOffice/", IsWrapped = true)]
    public partial class ObtenerProductosPorClienteResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://prosoft.CGPbackOffice/", Order = 0)]
        public E_Resultado ObtenerProductosPorClienteResult;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://prosoft.CGPbackOffice/", Order = 1)]
        public CL_ProductoCliente[] productos;

        public ObtenerProductosPorClienteResponse()
        {
        }

        public ObtenerProductosPorClienteResponse(E_Resultado ObtenerProductosPorClienteResult, CL_ProductoCliente[] productos)
        {
            this.ObtenerProductosPorClienteResult = ObtenerProductosPorClienteResult;
            this.productos = productos;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICoreInternoChannel : ICoreInterno, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CoreInternoClient : System.ServiceModel.ClientBase<ICoreInterno>, ICoreInterno
    {

        public CoreInternoClient()
        {
        }

        public CoreInternoClient(string endpointConfigurationName) :
                base(endpointConfigurationName)
        {
        }

        public CoreInternoClient(string endpointConfigurationName, string remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public CoreInternoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public CoreInternoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        public bool ServicioDisponible(int CodEmpresa)
        {
            return base.Channel.ServicioDisponible(CodEmpresa);
        }

        public CuentaIBAN_Response ObtenerCuentaIBAN(int CodEmpresa, CuentaIBAN_Request DatosCuenta)
        {
            return base.Channel.ObtenerCuentaIBAN(CodEmpresa, DatosCuenta);
        }

        public ValidacionPerfilTrx_Response ValidarPerfilTransaccional(ValidacionPerfilTrx_Request transaccion)
        {
            return base.Channel.ValidarPerfilTransaccional(transaccion);
        }

        public CL_ResultadoValidacion[] ValidaDebitos(SI_Rastro rastro, CL_DatosTransaccion[] transacciones)
        {
            return base.Channel.ValidaDebitos(rastro, transacciones);
        }


        public CL_ResultadoValidacion[] ValidaCreditos(SI_Rastro rastro, CL_DatosTransaccion[] transacciones)
        {
            return base.Channel.ValidaCreditos(rastro, transacciones);
        }


        public CL_ValidaCuenta ValidaCuenta(string Identificacion, string CuentaIBAN, int CodigoMoneda)
        {
            return base.Channel.ValidaCuenta(Identificacion, CuentaIBAN, CodigoMoneda);
        }

        public CL_ObtieneInfoCuenta ObtieneInfoCuenta(string Identificacion, string CuentaIBAN)
        {
            return base.Channel.ObtieneInfoCuenta(Identificacion, CuentaIBAN);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ObtieneEstadoTransaccionResponse ICoreInterno.ObtieneEstadoTransaccion(ObtieneEstadoTransaccionRequest request)
        {
            return base.Channel.ObtieneEstadoTransaccion(request);
        }

        public bool ObtieneEstadoTransaccion(string CodigoReferenciaSINPE, out string ComprobanteInterno)
        {
            ObtieneEstadoTransaccionRequest inValue = new ObtieneEstadoTransaccionRequest();
            inValue.CodigoReferenciaSINPE = CodigoReferenciaSINPE;
            ObtieneEstadoTransaccionResponse retVal = ((ICoreInterno)(this)).ObtieneEstadoTransaccion(inValue);
            ComprobanteInterno = retVal.ComprobanteInterno;
            return retVal.ObtieneEstadoTransaccionResult;
        }


        public CL_RespuestaTransaccion[] AplicaDebitosCongelados(SI_Rastro rastro, CL_Transaccion[] transacciones)
        {
            return base.Channel.AplicaDebitosCongelados(rastro, transacciones);
        }


        public CL_RespuestaTransaccion[] AplicaCreditosCongelados(SI_Rastro rastro, CL_Transaccion[] transacciones)
        {
            return base.Channel.AplicaCreditosCongelados(rastro, transacciones);
        }


        public CL_ResultadoActualizacion[] ConfirmaCreditosCongelados(SI_Rastro rastro, CL_ActualizaTransaccion[] transacciones)
        {
            return base.Channel.ConfirmaCreditosCongelados(rastro, transacciones);
        }


        public CL_ResultadoActualizacion[] ConfirmaDebitosCongelados(SI_Rastro rastro, CL_ActualizaTransaccion[] transacciones)
        {
            return base.Channel.ConfirmaDebitosCongelados(rastro, transacciones);
        }


        public CL_RespuestaTransaccion[] AplicaTransferenciasFirmes(SI_Rastro rastro, CL_Transaccion[] transacciones)
        {
            return base.Channel.AplicaTransferenciasFirmes(rastro, transacciones);
        }


        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SaldoDisponibleResponse ICoreInterno.SaldoDisponible(SaldoDisponibleRequest request)
        {
            return base.Channel.SaldoDisponible(request);
        }

        public E_Resultado SaldoDisponible(SI_Rastro rastro, string cuentaIBAN, string identificacion, int codigoMoneda, decimal monto, int codigoServicio, out bool disponible)
        {
            SaldoDisponibleRequest inValue = new SaldoDisponibleRequest();
            inValue.rastro = rastro;
            inValue.cuentaIBAN = cuentaIBAN;
            inValue.identificacion = identificacion;
            inValue.codigoMoneda = codigoMoneda;
            inValue.monto = monto;
            inValue.codigoServicio = codigoServicio;
            SaldoDisponibleResponse retVal = ((ICoreInterno)(this)).SaldoDisponible(inValue);
            disponible = retVal.disponible;
            return retVal.SaldoDisponibleResult;
        }


        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ComisionRespectivaResponse ICoreInterno.ComisionRespectiva(ComisionRespectivaRequest request)
        {
            return base.Channel.ComisionRespectiva(request);
        }

        public E_Resultado ComisionRespectiva(SI_Rastro rastro, string cuentaIBAN, string identificacion, int codigoMoneda, decimal monto, int codigoServicio, out decimal comision, out int codigoMonedaComision)
        {
            ComisionRespectivaRequest inValue = new ComisionRespectivaRequest();
            inValue.rastro = rastro;
            inValue.cuentaIBAN = cuentaIBAN;
            inValue.identificacion = identificacion;
            inValue.codigoMoneda = codigoMoneda;
            inValue.monto = monto;
            inValue.codigoServicio = codigoServicio;
            ComisionRespectivaResponse retVal = ((ICoreInterno)(this)).ComisionRespectiva(inValue);
            comision = retVal.comision;
            codigoMonedaComision = retVal.codigoMonedaComision;
            return retVal.ComisionRespectivaResult;
        }


        public CL_ResultadoActualizacion[] ReversaCreditos(SI_Rastro rastro, TransaccionRechazada[] transacciones)
        {
            return base.Channel.ReversaCreditos(rastro, transacciones);
        }


        public CL_ResultadoActualizacion[] ReversaDebitos(SI_Rastro rastro, TransaccionRechazada[] transacciones)
        {
            return base.Channel.ReversaDebitos(rastro, transacciones);
        }


        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ObtenerInformacionClienteResponse ICoreInterno.ObtenerInformacionCliente(ObtenerInformacionClienteRequest request)
        {
            return base.Channel.ObtenerInformacionCliente(request);
        }

        public E_Resultado ObtenerInformacionCliente(string identificacion, out CL_InformacionCliente informacionCliente)
        {
            ObtenerInformacionClienteRequest inValue = new ObtenerInformacionClienteRequest();
            inValue.identificacion = identificacion;
            ObtenerInformacionClienteResponse retVal = ((ICoreInterno)(this)).ObtenerInformacionCliente(inValue);
            informacionCliente = retVal.informacionCliente;
            return retVal.ObtenerInformacionClienteResult;
        }


        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ObtenerProductosPorClienteResponse ICoreInterno.ObtenerProductosPorCliente(ObtenerProductosPorClienteRequest request)
        {
            return base.Channel.ObtenerProductosPorCliente(request);
        }

        public E_Resultado ObtenerProductosPorCliente(string identificacion, out CL_ProductoCliente[] productos)
        {
            ObtenerProductosPorClienteRequest inValue = new ObtenerProductosPorClienteRequest();
            inValue.identificacion = identificacion;
            ObtenerProductosPorClienteResponse retVal = ((ICoreInterno)(this)).ObtenerProductosPorCliente(inValue);
            productos = retVal.productos;
            return retVal.ObtenerProductosPorClienteResult;
        }


        public CL_ResultadoTipoCambio ObtenerTipoCambio(SI_Rastro Rastro, int CodigoServicio, string CuentaOrigen, string CuentaDestino, decimal Monto, int Moneda)
        {
            return base.Channel.ObtenerTipoCambio(Rastro, CodigoServicio, CuentaOrigen, CuentaDestino, Monto, Moneda);
        }


        public bool ActualizarFechaCiclo(int ComprobanteCGP, string DocumentoSistemaInterno, int ServicioSINPE, System.DateTime FechaCiclo, string CodigoReferenciaAnterior, string CodigoReferenciaNuevo)
        {
            return base.Channel.ActualizarFechaCiclo(ComprobanteCGP, DocumentoSistemaInterno, ServicioSINPE, FechaCiclo, CodigoReferenciaAnterior, CodigoReferenciaNuevo);
        }


        public bool LiquidarCiclo(int[] EntidadesAplazadas, int ServicioSINPE, string Modalidad, System.DateTime FechaCiclo)
        {
            return base.Channel.LiquidarCiclo(EntidadesAplazadas, ServicioSINPE, Modalidad, FechaCiclo);
        }


        public CL_RespuestaNotificacion[] PreferenciasNotificacion(SI_Rastro rastro, CL_Notificacion[] notificacion)
        {
            return base.Channel.PreferenciasNotificacion(rastro, notificacion);
        }

    }

}